version: '3.8'

services:
    database:
        platform: linux/amd64
        container_name: database
        image: mysql:8.0
        command: --default-authentication-plugin=mysql_native_password
        environment:
            MYSQL_ROOT_PASSWORD: Ch4ng3MePlease!
            MYSQL_DATABASE: xperience
            MYSQL_USER: xperience
            MYSQL_PASSWORD: xp3ri3nc3
        ports:
            - '4306:3306'
        volumes:
            - ./infra/mysql:/var/lib/mysql
    php:
        platform: linux/amd64
        container_name: php
        build:
            context: ./infra/php
        ports:
            - '9000:9000'
        volumes:
            - ./web-app:/var/www/symfony_docker
        depends_on:
            - database
    nginx:
        platform: linux/amd64
        container_name: nginx
        image: nginx:stable-alpine
        ports:
            - '8080:80'
        volumes:
            - ./web-app:/var/www/symfony_docker
            - ./infra/nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - php
            - database
